### ISSUE TITLE
support for zsh

### ISSUE THREAD

**Issue by rohit-zabbed** [cloudposse/geodesic#112]
## what
* Do not require `bash4`
* Would be great if we can support `zsh` as well.

## why
* The default script requires bash4 which enforce to have separate bash installation (e.g. via `brew`)

**Comment by osterman** [comment]
I agree. I want to drop this requirement. =)

Might be simplifying/refactoring the wrapper script to accommodate that. Thanks for speaking up!

**Comment by osterman** [comment]
@rohit-zabbed we've restored compatibility with bash 3, so it's no longer necessary to install `bash4`

**Comment by osterman** [comment]
@rohit-zabbed can you elaborate on the zsh support you want?

**Comment by osterman** [comment]
Bash for the foreseeable future will remain the primary language for scripting integrations between all the various tools.
