### ISSUE TITLE
Add Support for a Dotfile Manager

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#148]
## what
* Provide a standard interface for shell extensions 
* Re-use some existing standard

## why
* Allow users to define their own aliases, prompts, inputrcs, etc

## references
- <https://github.com/dotphiles/dotphiles>
- <https://github.com/TheLocehiliosan/yadm>

**Comment by mike-zipit** [comment]
For @tamsky and @Erik Osterman -- .inputrc, prompt and all this fall under this rubric of "dotfile" management.  IMO, the way to approach this is:
* Move any files that are "user breakable" from `/etc/profile.d` into a `cloudeposse/geodesic-dotfiles` (which has the default configuration for environment, prompt, anything shell related)
* `Dockerfile` for geodesic has something like:
```
ENV USER_HOME=https://github.com/cloudposse/geodesic-dotfiles
RUN curl -fLo /usr/local/bin/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm && chmod a+x /usr/local/bin/yadm
RUN cd /conf && yadm clone $USER_HOME
```
* This would put the user in control of their bash setup -- they could clone the "breakable" dotfiles from `cloudposse/geodesic-dotfiles` and then add their custom settings

**Comment by osterman** [comment]
I'm going to close this for now. I think the best place for this is in images that extend from geodesic. Also, see the multi-stage docker build pattern. That's another great approach to introducing extensions. I may revist dotfiles managers in the future as we continue to decompose geodesic into more purpose built "modules" like `helmfiles` and `packages`
