### ISSUE TITLE
Move All Helmfile Values Inline

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#169]
## what
* Use inline values 

## why
* More concise format
* Does not require external file
* Does not require YAML-selectors

## example

https://github.com/cloudposse/geodesic/blob/b6e46f4deba3aa108a081c26ea868a6ad15511bd/rootfs/conf/kops/helmfile.yaml#L445-L481

**Comment by osterman** [comment]
Let's first implement https://github.com/cloudposse/geodesic/issues/157

**Comment by alebabai** [comment]
Should i also refactor `set` with inline values?

**Comment by osterman** [comment]
Is this done now?

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/helmfiles
