### ISSUE TITLE
Install chartmuseum without tls

### ISSUE THREAD

**Issue by daveyu** [cloudposse/geodesic#183]
## what
* `helmfile.yaml` sets `ingress.tls[0].secretName` and `ingress.tls[0].hosts[0]` for the chartmuseum releases
* Make these values optional

## why
* Allow chartmuseum charts to be installed without tls

**Comment by daveyu** [comment]
In the meantime, I will maintain my own `helmfile.yaml` with these values commented out:

https://github.com/cloudposse/geodesic/blob/master/rootfs/conf/kops/helmfile.yaml#L153-L158
https://github.com/cloudposse/geodesic/blob/master/rootfs/conf/kops/helmfile.yaml#L259-L264

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/helmfiles/pull/21
