### ISSUE TITLE
Add Support for Windows (WSL/Ubuntu Linux)

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#196]
## what
* Add support for running Geodesic shells on [Windows using WSL](https://docs.microsoft.com/en-us/windows/wsl/about)

## why
* We have some early adopters running windows
* Minimal effort seems required to get this working on windows (seems very close!)

## references
*  https://github.com/cloudposse/root.cloudposse.co/issues/6
* https://github.com/cloudposse/geodesic/issues/199

**Comment by vadim-hleif** [comment]
Implemented

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/geodesic/pull/202
