### ISSUE TITLE
Historical command line editing is broken

### ISSUE THREAD

**Issue by Nuru** [cloudposse/geodesic#212]
## what
Concerning version 0.12.6. Also reproduced in 0.11.0.

Editing historical command lines using emacs keys is broken in certain circumstances. My guess is that it has to do with a divergence between the actual length of the prompt when output versus the length of the prompt when queried by the command line editor.

Reproducing this bug is a little tricky. This seems to work for me, but you might have to try some variations.

1. Enter a long command at the command line:
    ```
    echo top level this is a long command
    ```
1. Press the up-arrow &uparrow; to recall the command to the command line.
1. Press ctrl-A to move the cursor to the beginning of the command line.

Expected: cursor hovers over "e" in echo.
Observed: cursor hovers over "c" in echo.

## why
Not only does this cause difficulty in editing historical command lines, it results in a dangerous situation where the command visible on the command line is not exactly what will be submitted when you hit return.

**Comment by osterman** [comment]
What version are you using?

You can set `PROMPT_STYLE=plain` which will probably eliminate your problems

**Comment by Nuru** [comment]
Using `0.12.6`. Previously using `0.11.0` which did not have this problem.

`PROMPT_STYLE=plain` does not solve the problem.

Commenting out `PROMPT_HOOKS+=("geodesic_prompt")` from `/etc/profile.d/prompt.sh` eliminates the issue (and the nice prompt) but of course does not survive a restart of the container.

**Comment by Nuru** [comment]
Replacing `/etc/profile.d/prompt.sh` with version from `0.9.18` does not solve the problem, nor does unsetting `PROMPT_HOOKS`.

**Comment by osterman** [comment]
This is what I see in iTerm2:

![image](https://user-images.githubusercontent.com/52489/43758379-c9c60840-99d0-11e8-9040-56a15bebced1.png)

Maybe related to my terminal (why it works). 

Can you try just radically simplifying the prompt characters in `/etc/profile.d` and removing all the `tput` statements. 

If that works, we can introduce another prompt format.

**Comment by Nuru** [comment]
I'm using the OS X Terminal. I seem to see some improvement in Terminal if I turn on the "Unicode East Asian Ambiguous characters are wide" option in Terminal -> Preferences -> Advanced, but not complete solution. What do you see when you search for "echo" and then start to edit the line (key sequence `ctrl-R e c h o ctrl-A`)? I see a colon left over from search and the cursor over the space between the colon and the "e" in "echo".

![image](https://user-images.githubusercontent.com/2793313/43767902-fe006668-99ea-11e8-9832-70f50ea1d6f2.png)

**Comment by osterman** [comment]
Okay, I think we'll introduce a new prompt style that uses these gyphs: `0x20E0`, `0x2234`
∴ ⃠

**Comment by Nuru** [comment]
FWIW, I reproduced the issues in iTerm2 version 3.1.7. The problem goes away in iTerm2 if the option "Use Unicode Version 9 widths" it enabled. Documentation for this feature says "Unicode version 9 offers better formatting for Emoji." 

Glyphs `0x20E0` and `0x2234` seem to have the same problem of being double-width and messing up Terminal. Using those in the prompt will not solve this issue.

**Comment by Nuru** [comment]
I suggest you use these single-width glyphs instead. 
✗
BALLOT X
Unicode: U+2717, UTF-8: E2 9C 97

✓
CHECK MARK
Unicode: U+2713, UTF-8: E2 9C 93

⨠
Z NOTATION SCHEMA PIPING
Unicode: U+2A20, UTF-8: E2 A8 A0

**Comment by osterman** [comment]
Fixed in https://github.com/cloudposse/geodesic/releases/tag/0.15.0
