### ISSUE TITLE
Move Pip Installation to `requirements.txt`

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#232]
## what
* Move all python requirements to `requirements.txt`
* Use multi-stage build pattern as described here: https://blog.realkinetic.com/building-minimal-docker-containers-for-python-applications-37d0272c52f3

```
FROM python:3.6-alpine as base
FROM base as builder
RUN mkdir /install
WORKDIR /install
COPY requirements.txt /requirements.txt
RUN pip install --install-option="--prefix=/install" -r /requirements.txt
FROM base
COPY --from=builder /install /usr/local
```

## why
* Rely on python package management
* Automatic package updates by Dependabot

**Comment by alebabai** [comment]
Did you mean all pip packages in dockerfile?

**Comment by osterman** [comment]
Fixed in https://github.com/cloudposse/geodesic/pull/253/commits/7d9c8ec351f7cfc4447e8010c2ba537b9947ef9d
