### ISSUE TITLE
Release 0.16.1 - broke geodesic shell

### ISSUE THREAD

**Issue by goruha** [cloudposse/geodesic#236]
## what
* Release https://github.com/cloudposse/geodesic/tree/0.16.1 broke shell

## How to reproduce
* `make build` - Build geodesic module from geodesic:0.16.1
* `make install` - Install geodesic module
* `$CLUSTER_NAME` - run into shell

## Expect 
* Got shell command line

## Exists
* 
```
goruha@goruha-laptop ~/projects/cloudposse/example.com (feature-collect-logs●●)$ example.com                                                  [ruby-2.5.1p57]
# Mounting /home/goruha into container
# Starting new example.com session from r.cfcr.io/example.com:latest
# Exposing port 39257

```
* When I click `Ctlr+D` I got 
```
goruha@goruha-laptop ~/projects/cloudposse/example.com (feature-collect-logs●●)$ example.com                                                  [ruby-2.5.1p57]
# Mounting /home/goruha into container
# Starting new example.com session from r.cfcr.io/example.com:latest
# Exposing port 39257
^C04da1f47d29c:~#
```

**Comment by osterman** [comment]
What broke?

It's not clear to me from the description

**Comment by osterman** [comment]
![image](https://user-images.githubusercontent.com/52489/44492159-55942c00-a618-11e8-958d-333de3bf5653.png)

**Comment by osterman** [comment]
Okay, @vadim-hleif was able to reproduce this. It's related to the `curl` test for metadata api.
