### ISSUE TITLE
Move Kops to Submodule

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#306]
## what
* move `kops` to geodesic submodule (`geodesic-aws-kops`)

## why
* So we can version it separately from geodesic

**Comment by Nuru** [comment]
@osterman How far do #439 and https://github.com/cloudposse/reference-architectures/pull/21 get you to where you want to be with respect to making `kops` a separate module?

**Comment by Nuru** [comment]
Closed via #945 which removed `kops` entirely
