### ISSUE TITLE
Perceived Inconsistencies

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#317]
## what
* Identify and address inconsistencies 

## why
* we cannot begin to standardize something which is inconsistent.

**Comment by osterman** [comment]
When do variables go in the `Dockerfile` vs somewhere else? e.g. `.tfvar` file or `.envrc`?

**Comment by osterman** [comment]
Why are some variables prefixed with `TF_VAR_` but not others?

**Comment by jdn-za** [comment]
Needing to have some env vars set in the dockerfiles during cold start and others set empty or not set is very unintuitive

**Comment by osterman** [comment]
There's kind of a discrepancy between the expectation of running `make docker/build` locally, vs pulling down an image. When would we pull down an image and run from that vs building locally and running?

**Comment by jdn-za** [comment]
Also the needing to comment out assume role in the root dockerfile while also then using sed to comment out the backend in the same file makes me sad.

https://unix.stackexchange.com/questions/26284/how-can-i-use-sed-to-replace-a-multi-line-string

Is what I would look at, though have not as yet done so

**Comment by osterman** [comment]
> Also the needing to comment out assume role in the root dockerfile while also then using sed to comment out the backend in the same file makes me sad.

Hah, me too. Just to be precise, are you referring to this? https://github.com/cloudposse/terraform-root-modules/blob/master/aws/tfstate-backend/scripts/init.sh

**Comment by osterman** [comment]
![image](https://user-images.githubusercontent.com/52489/49364572-78af8c80-f699-11e8-9aca-347e991bab34.png)

![image](https://user-images.githubusercontent.com/52489/49364607-8d8c2000-f699-11e8-864d-022d6650cd54.png)

**Comment by osterman** [comment]
The issues raised here have been addressed in the following PRs:
- https://github.com/cloudposse/reference-architectures/pull/1
- https://github.com/cloudposse/reference-architectures/pull/2
- https://github.com/cloudposse/geodesic/pull/330
- https://github.com/cloudposse/geodesic/pull/332
- https://github.com/cloudposse/geodesic/pull/335
- https://github.com/cloudposse/terraform-root-modules/pull/70
- https://github.com/cloudposse/terraform-root-modules/pull/69
- https://github.com/cloudposse/terraform-root-modules/pull/68
- https://github.com/cloudposse/terraform-root-modules/pull/67
- https://github.com/cloudposse/terraform-root-modules/pull/66
- https://github.com/cloudposse/terraform-root-modules/pull/64
- https://github.com/cloudposse/terraform-root-modules/pull/63
- https://github.com/cloudposse/terraform-root-modules/pull/61
- https://github.com/cloudposse/terraform-root-modules/pull/60
- https://github.com/cloudposse/terraform-root-modules/pull/56

**Comment by osterman** [comment]
Basically, we've made the following wide sweeping changes
* Radically reduce the number of environment variables that need to be set
* Allow environment variables to be consistently named (e.g. with `TF_VAR_` prefix) by using `tfenv`
* Do not default to sticking environment variables in the `Dockerfile` as it is overwhelming and *not* clear what projects consume them
* Rely on `.tfvar` files for terraform settings (non-secrets); b/c defining maps and lists in envs for terraform as environment variables is ugly/error prone and seldom need to be used outside of terraform
* Rely on `.envrc` (aka `direnv`) for all other project settings 
* Use terraform remote state to reduce env passing / hardcoding

**Comment by osterman** [comment]
@jdn-za closing this issue. We can open up new issues if you find other inconsistencies. The "cold start" automation exercise in the `reference-architectures` projects forced us to adopt some extreme consistency.
