### ISSUE TITLE
Dont set docker DNS

### ISSUE THREAD

**Issue by jdn-za** [cloudposse/geodesic#320]
## what
doing a `assume-role` in a geodesic container while on a network that **does not allow** using any external DNS servers directly, which is very common in corporate networks, results in a timeout for sts.amazonaws.com

```
-> Run 'assume-role' to login to AWS
 ⧉  users.aws.example.org
 ✗   (none) ~ ⨠  assume-role
Enter passphrase to unlock /conf/.awsvault/keys/:
Enter token for arn:aws:iam::883075610859:mfa/bootStrap: 395604
2018/12/05 13:55:44 Request body type has been overwritten. May cause race conditions
2018/12/05 13:55:54 Request body type has been overwritten. May cause race conditions
2018/12/05 13:56:04 Request body type has been overwritten. May cause race conditions
aws-vault: error: Failed to get credentials for example (source profile for example-users-bootstrap): RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: dial tcp: lookup sts.amazonaws.com on 8.8.8.8:53: read udp 172.17.0.2:40888->8.8.8.8:53: i/o timeout
```
I would not set DNS to anything as it makes the assumption that one can access google DNS.

https://github.com/cloudposse/geodesic/blob/master/rootfs/templates/wrapper#L261

**Comment by osterman** [comment]
@jdn-za agreed - I'm going to drop that. I think it's left overs from a long time ago. Had some issues with DNS resolution in docker.

**Comment by osterman** [comment]
For the record, it was implemented due to https://github.com/docker/docker/issues/24344

**Comment by jdn-za** [comment]
Thanks gents
