### ISSUE TITLE
WSL Bugs

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#379]
## what
* Not working on some WSL environments

Here is a list of the changes I had to make to get root.cloud.posse script to run on WSL:

In root.*.com:
1. `DOCKER_NAME` was using `$NAME` environment variable. For me `$NAME` was all caps and docker complained that name must be all lowercase
2. On lines 112-116 of root.*.com you have
```
            for dir in $mount_path/c/Users/${windows_user_name}/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu*; do
                folder_name=$(basename ${dir})
                local_home=${user_local_app_data}/Packages/${folder_name}/LocalState/rootfs${HOME}
                break
            done
```

- for me `${windows_user_name}` contained spaces, which led to wrong `mount_path`

3. In docker run command that gets generated from the script you have `--name` parameter twice

4. In docker run command that gets generated from the script you need quotes around the argument for `--volume`

   e.g. `--volume="path/to/volume"` instead of `--volume=path/to/volume`

   My volume path had spaces so without it would take wrong path

**Comment by Nuru** [comment]
Closing as stale now that WSL v1 is obsolete and the current WSL2 does not seem to have these problems. If there are issues with Geodesic under WSL2, please open a new issue.
