### ISSUE TITLE
Running Non-Interactive

### ISSUE THREAD

**Issue by marwanhilmi** [cloudposse/geodesic#382]
## Running Non-Interactive (on a CI system)
I am wondering if / how it is possible to run a `geodesic` container in a non-interactive environment. The idea is that I want to package the infrastructure into a container (ala `prod.cloudposse.co` or others) and then use that container on a CI system to perform deploys.

So far these are the steps I've taken but I'm wondering if there's an easier or existing method:
- Create a IAM system user with appropriate permissions (with `aws_access_key_id` and `aws_secret_access_key`)
- Boot into the container without the wrapper script ie `docker run -it --entrypoint /bin/bash cloudposse/prod.cloudposse.co`
- Create a `/conf/.aws/credentials` file inside the container with IAM user from previous step
- In the terraform directory we are trying to use, create an `override.tf` where we reset the default `aws` provider in order to override `var.aws_assume_role_arn`
```
provider "aws" {
  assume_role {
    role_arn = "${var.aws_assume_role_arn}"
  }
}
```
=>
```
provider "aws" {}
```

So obviously a lot of manual hacking of the credentials is required to make this work. 
- Is there an easier way? 
- Can I possibly bootstrap the container with credentials beforehand similarly to how the interactive bootstrap works?
- How can I toggle the `provider "aws"` so it can be re-usable in both fashions without needing an override? For reference I am attempting to run this container on a EC2 instance where the host has the necessary permissions (ie Terraform should fetch credentials from AWS metadata endpoint).

Thanks for the assistance!

**Comment by osterman** [comment]
@marwanhilmi we do this today actually using Atlantis + ECS Fargate. 

The high-level idea is that you deploy to ECS Fargate  geodesic as an ECS Task with `atlantis` pre-baked into the image. Then tie it together with GitHub webhooks. 

Don't provision IAM credentials; those are for humans. Instead, use IAM roles assigned to ECS tasks. That way they are constantly rotated and invalidated.

We implement this strategy here: http://github.com/cloudposse/terraform-aws-ecs-atlantis

**Comment by osterman** [comment]
http://runatlantis.io

**Comment by marwanhilmi** [comment]
@osterman Thanks for the reply! Indeed you are correct about the IAM role. I initially wasn't able to figure out why I couldn't get the `aws provider` to work without hardcoded credentials but I realized some of the default `AWS_` env variables set inside the image were tripping up Terraform.

The host EC2 instance has an IAM role with suitable permissions so I was able to wire up simple script like below to get it to work. Terraform then fetches IAM role via EC2 metadata API which is available inside the container instead of `assume-role`.

```
# init-for-ci.sh
#!/bin/bash

echo "🚨 Overriding default AWS parameters..."
export AWS_CONFIG_FILE=
export AWS_SHARED_CREDENTIALS_FILE=
export AWS_DATA_PATH=

echo "🚨 Overriding default Terraform provider.aws..."
tee ./override.tf > /dev/null << EOF
provider "aws" {}
EOF
```

Will look into Atlantis, thanks for the tip!
