### ISSUE TITLE
 `assume-role` interactive does not works on linux

### ISSUE THREAD

**Issue by goruha** [cloudposse/geodesic#391]
## what
* `assume-role` interactive does not works on linux

```
 ✗   (none) ~ ⨠ assume-role
Failed to read /dev/tty
Usage: assume-role [role]
```

**Comment by osterman** [comment]
I use linux and it works. Can you add some more context?

![image](https://user-images.githubusercontent.com/52489/53627585-aedbaa00-3bbd-11e9-9d29-92c305b3425c.png)

**Comment by osulli** [comment]
Can confirm the same on Ubuntu tt

```
 ⧉  sandbox 
 ✓   (healthera-sandbox-admin) vpc_peering ⨠ terraform apply
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```

**Comment by osterman** [comment]
@osulli please share a screenshot of what you see as @goruha's problem was fixed in https://github.com/cloudposse/geodesic/pull/390.

**Comment by osulli** [comment]
@osterman 


![image](https://user-images.githubusercontent.com/46930728/54134806-8307c200-4410-11e9-8523-1dc76a5bb4a0.png)

**Comment by osulli** [comment]
I think I'm actually reporting a different issue.. I saw the broken character in @goruha's stdout and thought it was the same.
I'm just reporting the broken character when on Ubuntu.

**Comment by osulli** [comment]
@osterman moved my issue to #417 .
Don't think my comments are related to #391.

**Comment by osterman** [comment]
@osulli thanks for reporting. Ok, I think we need to change up the prompt characters.

for now, you can set `PROMPT_STYLE=plan`

**Comment by osterman** [comment]
@osulli I am confused b/c this output looks good: https://github.com/cloudposse/geodesic/issues/391#issuecomment-471577806

while this looks bad: https://github.com/cloudposse/geodesic/issues/391#issuecomment-471581782

**Comment by osterman** [comment]
It appears this `⨠` utf8 character is the problem.

**Comment by osterman** [comment]
going to close this for now, but we'll address your other issue
