### ISSUE TITLE
Add `TF_BUCKET_PREFIX_FORMAT` 

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#401]
## what
Add `TF_BUCKET_PREFIX_FORMAT`

## why
* we can have one format be `pwd` and other format be `basename` or `basename-pwd` 
* `basename` is not sufficiently disambiguated when working with multi-region (e.g. `conf/us-west-2/vpc`)

## references
* https://github.com/cloudposse/geodesic/blob/master/rootfs/etc/direnv/rc.d/terraform#L16

**Comment by raehik** [comment]
There are various usages for this, generally useful for accounts which store the same module multiple times (e.g. multiple regions, clusters, VPCs). And as a general structuring tool so you don't have 50 flat modules in `/conf`.

I'm working on this. Where should the documentation for this go? Worth chucking a note in a default config file?

**Comment by osterman** [comment]
@raehik thanks so much! Yes, this is a much needed improvement and a quick win.

Maybe add a note here? https://github.com/cloudposse/geodesic/blob/master/docs/design.md#layout-inside-the-shell
