### ISSUE TITLE
Document Geodesic proxy port 

### ISSUE THREAD

**Issue by raehik** [cloudposse/geodesic#448]
## what
* Update name of and document usage of `$KUBERNETES_API_PORT` environment variable

## why
* Geodesic provides the above envvar and maps it from the container to the host, so you can easily do `kubectl port-forward` and `kubectl proxy` commands inside the container. Its existence is not well-documented, and the name used is somewhat confusing (could be used for any port forwarding).
* Better discoverability, more docs

**Comment by raehik** [comment]
related issue https://github.com/cloudposse/docs/issues/428

**Comment by raehik** [comment]
@osterman suggested `$GEODESIC_PORT` -- also the same envvar I searched for originally

**Comment by osterman** [comment]
@Nuru what do you think about this?

**Comment by Nuru** [comment]
@osterman I think changing the name of the variable is good, and I did it in #452 -> release 0.95.0. If we could get some open source heroes to do documentation, that would be great. At the moment I don't know what to tell people who are looking for documentation on Geodesic other than to watch your demos and read the code.
