### ISSUE TITLE
this looks amazing but is it only for AWS ?

### ISSUE THREAD

**Issue by vesper8** [cloudposse/geodesic#451]
This looks great and just what I'm looking for.. except for that fact that I don't roll with AWS. There are so many cool projects that only cater to AWS.. is this another one?

Can this be used *at all* when working with other VPS providers such as DigitalOcean?

**Comment by osterman** [comment]
@vesper8 thanks for checking out geodesic! 

Good question. So one of our own developers (@goruha) uses geodesic with Digital Ocean. We also have the `doctl` cli in our [`cloudposse/packages`](https://github.com/cloudposse/packages) repo. What this means is that when you use `geodesic` for your project, do something like this:

```
FROM cloudposse/geodesic:x.y.z`

RUN apk add --update doctl@cloudposse

```
Where `x.y.z` is some version of [`geodesic`](https://github.com/cloudposse/geodesic/releases)

Right now, we don't have anything in the way of "best practices" for digital ocean. We do intend to add more examples for that and have considered it an "easier" (and affordable) way to get started with kubernetes.
