### ISSUE TITLE
General Enhancements

### ISSUE THREAD

**Issue by osterman** [cloudposse/geodesic#615]
## what
- Only use `--privileged` mode when using `aws-vault` (see https://github.com/cloudposse/geodesic/pull/143) or as needed. but we should default to not using it so files are not owned by `root`. #139 
- Support a feature flag so we do not reattach to existing session

**Comment by Nuru** [comment]
I am closing this:

- Getting rid of the `--privileged` flag appears to be asking too much. We might be able to reduce it to `--cap-add SYS_ADMIN`, but that is not much of an improvement. So closing as `wontfix` but you can open a separate, isolated issue to discuss this if you want to.
- #961 adds a feature flag so we do not reattach to existing session
