### ISSUE TITLE
assume-role does not successfully pick up aws-vault SSO session 

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/geodesic#698]
## Describe the Bug

Couple things going on with `assume-role` that I perceive as issues, but figure it's possible I'm doing something wrong as well. First let me just share the screenshot of a reproduction of what I'm referring to: 

![image](https://user-images.githubusercontent.com/1392040/113778834-1b54fb80-96ea-11eb-852e-32078e61c126.png)

Issues: 

1. `assume-role` doesn't pick up SSO session correctly, which leads to #2
2. sub-shell created by assume-role improperly reports as `none` in prompt. Exiting that sub-shell leads to reporting the expected role's name in the prompt which is not correct either.

## Expected Behavior

1. `assume-role` would support existing aws-vault SSO sessions.
2. If a failed assume-role does happen then it doesn't create a sub-shell. If creating the sub-shell is necessary for some reason then it should not report in the shell prompt as `none` + report erroneously in the root shell. 

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Geodesic Debian
 - Version: v0.143.2

**Comment by Gowiem** [comment]
Side note: The error direct folks to call `aws sso login` as a resolution, but that subcommand is only available in awscliv2, which we do not include in Geodesic AFAIK.

**Comment by Nuru** [comment]
1. We do not currently support `aws sso` at all, although that is on our roadmap to do relatively soon.
2. When we do support it, we will support it with the native AWS SDK, including `aws` CLI v2. We have no plans to support AWS SSO via `aws-vault`. Our `aws-vault` support is heavily customized for the use case of handling static AWS API keys. AWS SSO makes all that unnecessary and so we do not expect to extend our `aws-vault` customization to cover that use case.
