### ISSUE TITLE
Prevent commands from showing up in history by setting `HISTCONTROL`

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/geodesic#750]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

Usually if you want to prevent saving commands in history, such as when using `chamber`, you want to prefix those commands with a space character.

Since the `HISTCONTROL` is unset, this causes all commands to show up in history even if the command is prefixed with a space.

Here is an example in geodesic

```
⨠ echo $HISTCONTROL

⨠  pw=helloworld
⨠ history | tail -2 | grep -v grep | grep pw
 2627   pw=helloworld
⨠ HISTCONTROL=ignoreboth
⨠  pw=helloworld
⨠ history | tail -2 | grep -v grep | grep pw
⨠
```

> HISTCONTROL
>
>    A colon-separated list of values controlling how commands are saved on the history list. If the list of values includes ‘ignorespace’, lines which begin with a space character are not saved in the history list. A value of ‘ignoredups’ causes lines which match the previous history entry to not be saved. A value of ‘ignoreboth’ is shorthand for ‘ignorespace’ and ‘ignoredups’. A value of ‘erasedups’ causes all previous lines matching the current line to be removed from the history list before that line is saved. Any value not in the above list is ignored. If HISTCONTROL is unset, or does not include a valid value, all lines read by the shell parser are saved on the history list, subject to the value of HISTIGNORE. The second and subsequent lines of a multi-line compound command are not tested, and are added to the history regardless of the value of HISTCONTROL.

https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html

**Comment by Nuru** [comment]
Not a bug, not an issue; preferences like this are why Geodesic has extensive runtime customization options. As delivered, Geodesic provides the default behavior of `bash`. If you don't like it, you can change it in your [preferences](https://github.com/cloudposse/geodesic/blob/d93d84e3957cdccc8e39e789b5a8062c2496924a/docs/customization.md).
