### ISSUE TITLE
AMD CPU got a warning for running Geodesic on Apple M1 CPU 🙂️

### ISSUE THREAD

**Issue by merrickluo** [cloudposse/geodesic#757]
https://github.com/cloudposse/geodesic/blob/fb64a1d2655de0cbc39c5ab7976cf36ccd0dc68f/rootfs/etc/profile.d/banner.sh#L9

I think the first check should be `$(arch) == "x86_64" ` instead of `!=`

**Comment by Nuru** [comment]
@merrickluo Thank you for reporting this. We don't have access to a computer demonstrating this problem, so we would appreciate your help resolving this. We need to find a test distinguishing an Apple M1 emulating an Intel CPU and your AMD CPU. 

An Apple M1 emulating an Intel CPU will report `arch` as `x86_64`. We distinguish that from the real `x86_64` via `cat /proc/cpuinfo` returning `vendor_id: GenuineIntel` among other info. What does your computer show for `vendor_id`? Is there something else in `/proc/cpuinfo` or elsewhere we can use to tell the difference between the M1 and your AMD?

**Comment by merrickluo** [comment]
Oh, seems I have the wrong assumption for M1. 
My `/proc/cpuinfo` report `vendor_id       : AuthenticAMD`, hope this helps.

**Comment by Nuru** [comment]
@merrickluo This should be fixed in Geodesic 0.149.1. Please try it out and update this ticket with your findings. You may reopen the ticket if you are still experiencing the problem.
