### ISSUE TITLE
Make all reports errors on exec format for awscli and session manager plugin

### ISSUE THREAD

**Issue by ghost** [cloudposse/geodesic#899]
**./aws/install: 78: /tmp/aws-inst-VbmBbTyu6r/aws/dist/aws: Exec format error**
You can now run: /usr/share/aws/v2/bin/aws --version
update-alternatives: using /usr/share/aws/v2/bin/aws to provide /usr/local/bin/aws (aws) in auto mode
Removing intermediate container e5ba3d9aa671
 ---> 1c0b4de03fa3
Step 72/83 : ENV AWS_PAGER="less -FRX"
 ---> Running in 6f525f1eacfe
Removing intermediate container 6f525f1eacfe
 ---> c0c269811dbe
Step 73/83 : ARG SESSION_MANAGER_PLUGIN_VERSION
 ---> Running in 05bb0b5d59b5
Removing intermediate container 05bb0b5d59b5
 ---> 9a71e0863840
Step 74/83 : RUN if [ "$TARGETARCH" = "amd64" ]; then       AWS_ARCH=64bit; else AWS_ARCH="$TARGETARCH"; fi &&     curl -L "https://s3.amazonaws.com/session-manager-downloads/plugin/${SESSION_MANAGER_PLUGIN_VERSION}/ubuntu_${AWS_ARCH}/session-manager-plugin.deb"     -o "/tmp/session-manager-plugin.deb" &&     sudo dpkg -i /tmp/session-manager-plugin.deb &&     rm /tmp/session-manager-plugin.deb
 ---> Running in d76af407c52b
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   243    0   243    0     0    455      0 --:--:-- --:--:-- --:--:--   455
**dpkg-deb: error: '/tmp/session-manager-plugin.deb' is not a Debian format archive**
dpkg: error processing archive /tmp/session-manager-plugin.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/session-manager-plugin.deb

**Comment by Nuru** [comment]
@fatporkrinds Thank you for reporting this issue. 

So we can reproduce it, please let us know more about how you ran into it:

- What host architecture were you running on? (If you have `go` installed, what is the output of `go env GOARCH`?) Geodesic is only supported on `amd64` (which includes the Intel x86_64 chips) and `arm64` (which includes the Apple M1/M2/M3 chips.
- What Dockerfile were you using? 
- What host OS were you running on? 
- What did you have `SESSION_MANAGER_PLUGIN_VERSION` set to?
- Were you running behind some kind of firewall or proxy? 

The output you posted shows that `curl` was not able to download the AWS Session Manager Plugin Debian package. The "243" as the 2nd and 4th numbers suggest that the URL was bad and the package not found at the constructed URL.

**Comment by Nuru** [comment]
Considering closed by #917. If problem persists, please reopen with the requested information.
