### ISSUE TITLE
Slim down container using slimtoolkit/slim

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/geodesic#947]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Since the release of version 3.0.0, the container is much smaller which is great. I think we can further slim down the container using

https://github.com/slimtoolkit/slim

## Use Case

I want the container to be even smaller

## Alternatives Considered

N/A

## Additional Context

- related #702

**Comment by GabisCampana** [comment]
@Nuru [DEV-2290 : Slim down container using slimtoolkit/slim](https://linear.app/cloudposse/issue/DEV-2290/slim-down-container-using-slimtoolkitslim)

**Comment by Nuru** [comment]
`slim` works by looking at what in the container gets used and removing stuff that is not used. That is appropriate if your container is an app and you have a test suite that provides 100% code coverage. 

Geodesic is not like that. Closing as `wontfix`.
